#server:
#  port: 8080
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306
#    username:
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#user:
#  id: 3
#  stepCount: 100